name: CI/CD to Vercel
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_APIKEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}
      NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECTID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECTID }}
      NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID }}
      NEXT_PUBLIC_FIREBASE_APPID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APPID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENTID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENTID }}
      NEXT_PUBLIC_FIREBASE_CLIENTID: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENTID }}
      NEXT_PUBLIC_FIREBASE_CLIENTSECRET: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENTSECRET }}
      NEXT_PUBLIC_DEV_EMAIL: ${{ secrets.NEXT_PUBLIC_DEV_EMAIL }}
      NEXT_PUBLIC_DEV_PASS: ${{ secrets.NEXT_PUBLIC_DEV_PASS }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_FIREBASE_PRIVATE_KEY_ID: ${{ secrets.NEXTAUTH_FIREBASE_PRIVATE_KEY_ID }}
      NEXTAUTH_FIREBASE_PRIVATE_KEY: ${{ secrets.NEXTAUTH_FIREBASE_PRIVATE_KEY }}
      NEXTAUTH_FIREBASE_CLIENT_EMAIL: ${{ secrets.NEXTAUTH_FIREBASE_CLIENT_EMAIL }}
      NEXTAUTH_FIREBASE_CLIENT_Id: ${{ secrets.NEXTAUTH_FIREBASE_CLIENT_Id }}
      NEXT_PUBLIC_BASEURL: ${{ secrets.NEXT_PUBLIC_BASEURL }}
      NEXT_PUBLIC_FOLDERID: ${{ secrets.NEXT_PUBLIC_FOLDERID }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_APIKEY: ${{ env.NEXT_PUBLIC_FIREBASE_APIKEY }}
          NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: ${{ env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECTID: ${{ env.NEXT_PUBLIC_FIREBASE_PROJECTID }}
          NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: ${{ env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: ${{ env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID }}
          NEXT_PUBLIC_FIREBASE_APPID: ${{ env.NEXT_PUBLIC_FIREBASE_APPID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENTID: ${{ env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID }}
          NEXT_PUBLIC_FIREBASE_CLIENTID: ${{ env.NEXT_PUBLIC_FIREBASE_CLIENTID }}
          NEXT_PUBLIC_FIREBASE_CLIENTSECRET: ${{ env.NEXT_PUBLIC_FIREBASE_CLIENTSECRET }}
          NEXT_PUBLIC_DEV_EMAIL: ${{ env.NEXT_PUBLIC_DEV_EMAIL }}
          NEXT_PUBLIC_DEV_PASS: ${{ env.NEXT_PUBLIC_DEV_PASS }}
          NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ env.NEXTAUTH_SECRET }}
          NEXTAUTH_FIREBASE_PRIVATE_KEY_ID: ${{ env.NEXTAUTH_FIREBASE_PRIVATE_KEY_ID }}
          NEXTAUTH_FIREBASE_PRIVATE_KEY: ${{ env.NEXTAUTH_FIREBASE_PRIVATE_KEY }}
          NEXTAUTH_FIREBASE_CLIENT_EMAIL: ${{ env.NEXTAUTH_FIREBASE_CLIENT_EMAIL }}
          NEXTAUTH_FIREBASE_CLIENT_Id: ${{ env.NEXTAUTH_FIREBASE_CLIENT_Id }}
          NEXT_PUBLIC_BASEURL: ${{ env.NEXT_PUBLIC_BASEURL }}
          NEXT_PUBLIC_FOLDERID: ${{ env.NEXT_PUBLIC_FOLDERID }}
          vercel-args: '--prod'
